[tool.pyright]
exclude = [".direnv", "result"]
ignore = ["cysensor/__init__.py"]
root = "."

[tool.ruff]
line-length = 79

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
extend_skip = ["result"]
